# Generated by Django 5.0.6 on 2024-07-03 12:52

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_migrate_translatable_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="shop.category",
            ),
        ),
    ]
